apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: manvsvirus
    name: backend
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080

